# Generated by Django 4.0.1 on 2022-01-15 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_sectionrelations_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionrelations',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_child', to='document.section'),
        ),
        migrations.AlterField(
            model_name='sectionrelations',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_parent', to='document.section'),
        ),
    ]
