# Generated by Django 4.0.1 on 2022-01-16 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_alter_section_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionrelations',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_child', to='document.section'),
        ),
    ]
