# Generated by Django 4.0.1 on 2022-01-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_alter_sectionrelations_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['-id']},
        ),
    ]
